### ISSUE TITLE
no pngs

### ISSUE THREAD

**Issue by benmosher** [kepeterson/BumperBlitz#1]
`*.png` in the `.gitignore` seems to have prevented all image assets from being committed.

Unable to build from clean checkout of `master`.

**Comment by kepeterson** [comment]
Hey Ben,

Thanks for checking out my code. I removed `*.png` from the `.gitignore` so all the assets are now in the repository as well. I just tested by cloning the repo into a new folder on my machine and launching Xcode from there and I can confirm the build worked. Let me know if you still have issues.

KP

**Comment by benmosher** [comment]
Works, thanks!
